[package]
name = "rustgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.3"
regex = "1.5.6"

tokio = "0.3.6"
rsocket_rust = "0.7.0"
rsocket_rust_transport_websocket = "0.7.0"
